force-app/main/default/objects/Cargo_Ship__c/Cargo_Ship__c.object-meta.xml
<CustomObject>
    <label>Cargo Ship</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargo Ships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/Container_Tracker__c.object-meta.xml
<CustomObject>
    <label>Container Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Container Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/fields/Cargo_Ship__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Ship__c</fullName>
    <label>Cargo Ship</label>
    <referenceTo>Cargo_Ship__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Tracker__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Tracker__c/fields/Container_Color__c.field-meta.xml
<CustomField>
    <fullName>Container_Color__c</fullName>
    <label>Container Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blue</fullName>
                <default>true</default>
                <label>Blue</label>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContainerCounterController.cls
public with sharing class ContainerCounterController {
	@AuraEnabled(cacheable=true)
	public static List<AggregateResult> getContainersCount() {
		List<AggregateResult> counterList = [SELECT Cargo_Ship__r.Name, Container_Color__c, COUNT(Container__c) Containers FROM Container_Tracker__c GROUP BY Cargo_Ship__r.Name, Container_Color__c];
		System.debug('AggregateResult: ' + counterList);
		return counterList;
	}
}