force-app/main/default/objects/Cargo_Ship__c/Cargo_Ship__c.object-meta.xml
<CustomObject>
    <label>Cargo Ship</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargo Ships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/Container_Tracker__c.object-meta.xml
<CustomObject>
    <label>Container Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Container Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/fields/Cargo_Ship__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Ship__c</fullName>
    <label>Cargo Ship</label>
    <referenceTo>Cargo_Ship__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Container_Tracker__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContainerTrackerController.cls
public with sharing class ContainerTrackerController {
	@AuraEnabled(cacheable=true)
	public static List<Container_Tracker__c> getContainersTracker() {
		return [SELECT Id, Name, Cargo_Ship__r.Name, Container__r.Name FROM Container_Tracker__c];
	}

	@AuraEnabled
	public static void deleteSelectedTrackers(List<Id> selectedTrackersIdList){
		List<Container_Tracker__c> trackerList = new List<Container_Tracker__c>();
		trackerList = [SELECT id FROM Container_Tracker__c WHERE id IN :selectedTrackersIdList];
		if(trackerList != null && trackerList.size() > 0) {
			delete trackerList;
		}
	}
}