force-app/main/default/objects/Container__c/fields/Transportation_Counter__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Counter__c</fullName>
    <label>Transportation Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container_Tracker__c/Container_Tracker__c.object-meta.xml
<CustomObject>
    <label>Container Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Container Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContainerTrackerHelper.cls
public with sharing class ContainerTrackerHelper {
	public static void calculateContainerAssignments(List<Container_Tracker__c> newContainerTracker) { //after insert
		Id[] cIds = new List<Id>();

		for (Container_Tracker__c trackerRec: newContainerTracker) {
			if (trackerRec.Container__c != Null) {
				cIds.add(trackerRec.Container__c);
			}
		}
	
		if(cIds.size() > 0) {
			List <Container__c> conList = new List <Container__c>();
			for (Container__c containerRec: [SELECT Transportation_Counter__c FROM Container__c WHERE id IN :cIds]) {
				if (containerRec.Transportation_Counter__c != Null) {
					containerRec.Transportation_Counter__c++;
				}
				else {
					containerRec.Transportation_Counter__c = 1;
				}
	
				if(containerRec.Transportation_Counter__c >= 4) {
					containerRec.Status__c = 'Need inspection';
				}
				conList.add(containerRec);
			}
			if (conList.size() > 0) {
				update conList;
			}
		} 
	}
}