force-app/main/default/objects/Container__c/fields/Transportation_Counter__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Counter__c</fullName>
    <label>Transportation Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Container_Tracker__c/Container_Tracker__c.object-meta.xml
<CustomObject>
    <label>Container Tracker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Container Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Containers Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Container_Tracker__c/fields/Container__c.field-meta.xml
<CustomField>
    <fullName>Container__c</fullName>
    <label>Container</label>
    <referenceTo>Container__c</referenceTo>
    <relationshipLabel>Containers Tracker</relationshipLabel>
    <relationshipName>Containers_Tracker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/helpers/ContainerTrackerHelper.cls
public with sharing class ContainerTrackerHelper {
	public static void calculateContainerAssignments() { //after insert

		Set <String> containerName = New Set <String>();

		for (Container_Tracker__c trackerRec: Trigger.new) {
		if (trackerRec.Container__c != Null) {
			String conName = [SELECT Name FROM Container__c WHERE id IN (Select Container__c FROM Container_Tracker__c WHERE Container_Tracker__c.Name = :trackerRec.Name)].Name;
			containerName.add(conName);
		}
	}

		if(containerName.size() > 0) {
			List <Container__c> conList = new List <Container__c>();
			for (Container__c containerRec: [SELECT id, Transportation_Counter__c FROM Container__c WHERE Name in: containerName]) {
				containerRec.Transportation_Counter__c++;
				if(containerRec.Transportation_Counter__c >= 4) {
					containerRec.Status__c = 'Need inspection';
				}
				conList.add(containerRec);
			}
			if (conList.size() > 0) {
				update conList;
			}
		} 
	}
}