force-app/main/default/objects/Container__c/fields/Transportation_Counter__c.field-meta.xml
<CustomField>
    <fullName>Transportation_Counter__c</fullName>
    <label>Transportation Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/helpers/ContainerHelper.cls
public with sharing class ContainerHelper {
	public static void startApproval(List<Container__c> newContainer) { //before insert, before update
		List<Approval.ProcessSubmitRequest> approvalList = new List<Approval.ProcessSubmitRequest>();

		for (Container__c containerRec: newContainer) {

			if(containerRec.Status__c == 'Need inspection' && containerRec.Transportation_Counter__c >= 5) {
				Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
				request.setComments('The container has 5 transactions. Please review record: ' + containerRec.id);
				request.setObjectId(containerRec.id);
				approvalList.add(request);
			}
		}
		List<Approval.ProcessResult> resultlist = Approval.process(approvalList);
	}
}